// FR-R3-065 — the visual preflight fails loudly, once, and never quietly passes.
//
// WHAT THIS GATE GUARANTEES
//
//   - a missing browser produces ONE setup failure, before any case launches,
//     carrying the resolved path and the install command;
//   - absent, stale, half-installed and shell-only are distinguishable, because
//     "install it" and "install it again" are different instructions to someone
//     who believes they already did — and telling a reader who can see a
//     populated cache that they have never installed is the same misdirection
//     the preflight exists to remove;
//   - BOTH Chromium builds are covered — the headed one `executablePath()` names
//     and the headless shell a headless launch actually starts;
//   - an indeterminate resolution FAILS rather than assuming the browser is there;
//   - the preflight never installs, never skips, and never exits 0 on a miss;
//   - no visual case has been skipped or weakened, and neither chain reordered,
//     to make the gate green.
//
// WHAT IT DOES NOT GUARANTEE
//
//   - It runs the preflight as a child process against a REDIRECTED cache
//     (`PLAYWRIGHT_BROWSERS_PATH`), never against the developer's real one. So it
//     proves the preflight's own behaviour, not that a particular machine is
//     provisioned. The latter is not a property a test should assert.
//   - The "no install" assertion is structural: the script contains no install
//     invocation. A script that shelled out through an indirection this does not
//     recognise would pass. Stated rather than implied — and the direct forms are
//     what a well-meaning future change would reach for.
//   - It asserts NO case count at all. The source finding is written in terms of
//     "eighteen specs", and copying that number here would reproduce the
//     stale-count defect FR-R3-067 is separately correcting — worse, it would be
//     wrong: the suite reports 18 cases from 4 literal `test(` calls, the rest
//     generated by parameterised loops. See the assertion below for what is
//     checked instead, and what is not.
import { execFileSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, rmSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve, join, dirname } from 'node:path';
import { afterAll, describe, expect, it } from 'vitest';

const REPO_ROOT = resolve(__dirname, '..', '..');
const PREFLIGHT = 'scripts/check-playwright-browser.mjs';
const VISUAL_SPEC = 'tests/visual/webview.visual.spec.ts';
const MARKER = 'visual-preflight:';

const read = (relPath: string): string => readFileSync(resolve(REPO_ROOT, relPath), 'utf8');

const scratchDirs: string[] = [];

function scratch(name: string): string {
  const dir = mkdtempSync(join(tmpdir(), `pw-preflight-${name}-`));
  scratchDirs.push(dir);
  return dir;
}

afterAll(() => {
  for (const dir of scratchDirs) rmSync(dir, { recursive: true, force: true });
});

interface RunResult {
  readonly status: number;
  readonly stdout: string;
  readonly stderr: string;
}

/** Run the preflight with the browser cache redirected. Never touches the real cache. */
function runPreflight(browsersPath: string): RunResult {
  try {
    const stdout = execFileSync('node', [PREFLIGHT], {
      cwd: REPO_ROOT,
      env: { ...process.env, PLAYWRIGHT_BROWSERS_PATH: browsersPath },
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe']
    });
    return { status: 0, stdout, stderr: '' };
  } catch (err) {
    const e = err as { status?: number; stdout?: string; stderr?: string };
    return { status: e.status ?? 1, stdout: e.stdout ?? '', stderr: e.stderr ?? '' };
  }
}

/**
 * The path the preflight says it looked for. Read back from its own output
 * rather than reconstructed here: a cache layout hardcoded in the test would
 * agree with a wrong script and disagree with a right one.
 */
function lookedFor(result: RunResult): string {
  const line = markerLines(result).find((entry) => entry.includes('Looked for: '));
  if (line === undefined) throw new Error(`no "Looked for:" line in: ${markerLines(result).join('\n')}`);
  return line.slice(line.indexOf('Looked for: ') + 'Looked for: '.length).trim();
}

/** Create an empty stub at `path`, parents included. Existence is all the preflight reads. */
function stub(path: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, '');
}

const markerLines = (result: RunResult): string[] =>
  `${result.stdout}\n${result.stderr}`.split('\n').filter((line) => line.includes(MARKER));

describe('visual preflight — a missing browser reports once (FR-R3-065)', () => {
  it('fails with a non-zero exit when the browser is absent', () => {
    const result = runPreflight(scratch('absent'));
    expect(result.status).not.toBe(0);
  });

  it('emits one setup failure, not one per visual case', () => {
    const result = runPreflight(scratch('single'));
    // The whole finding: eighteen per-case launch failures read as eighteen
    // broken tests. One block of setup output, and no per-case error, is the fix.
    expect(markerLines(result).length).toBeGreaterThan(0);
    expect(result.stderr).not.toContain("browserType.launch");
    expect(result.stderr).not.toContain('Executable doesn\'t exist');
    // Exactly one line asserts the failure itself; the rest are remedy detail.
    const headlines = markerLines(result).filter((line) => line.includes('is not installed'));
    expect(headlines).toHaveLength(1);
  });

  it('names the resolved path and the install command', () => {
    const dir = scratch('detail');
    const result = runPreflight(dir);
    const output = markerLines(result).join('\n');
    // The path is the fastest way to diagnose a redirected or half-downloaded
    // cache. This is a developer's terminal, not an audit payload.
    expect(output).toContain(dir);
    expect(output).toContain('npx playwright install chromium');
  });

  it('is identifiable as a setup failure from its first line', () => {
    const result = runPreflight(scratch('firstline'));
    const first = markerLines(result)[0];
    expect(first).toContain(MARKER);
    // A visual diff never says this. A contributor can tell the two apart without
    // reading a stack trace, which is the behaviour change this feature buys.
    expect(markerLines(result).join('\n')).toContain('not a visual regression');
  });

  it('distinguishes a never-provisioned cache from a stale one', () => {
    const absent = runPreflight(scratch('never'));
    const staleRoot = scratch('stale');
    mkdirSync(join(staleRoot, 'chromium-1200'), { recursive: true });
    const stale = runPreflight(staleRoot);

    expect(absent.status).not.toBe(0);
    expect(stale.status).not.toBe(0);

    const absentText = markerLines(absent).join('\n');
    const staleText = markerLines(stale).join('\n');
    expect(absentText).toContain('never been provisioned');
    expect(staleText).toContain('STALE');
    expect(staleText).toContain('chromium-1200');
    // Same failure, different instruction. The version-bump trigger makes the
    // stale case the common one, and telling that contributor to "install it"
    // when they already have is how a gate loses its reader.
    expect(absentText).not.toContain('STALE');
  });

  it('does not call a shell-only cache never provisioned', () => {
    // `--only-shell` and an interrupted install both leave a shell build with no
    // headed build beside it. "You have never installed" is false to someone
    // looking at a populated cache, and a diagnosis that contradicts what the
    // reader can see is the misdirection this preflight exists to remove. The
    // remedy is the same command either way; only the sentence changes.
    const root = scratch('shellonly');
    const shellDir = join(root, 'chromium_headless_shell-0000');
    mkdirSync(shellDir, { recursive: true });
    writeFileSync(join(shellDir, 'stub'), '');

    const result = runPreflight(root);
    expect(result.status).not.toBe(0);
    const text = markerLines(result).join('\n');
    expect(text).toContain('shell-only or interrupted install');
    expect(text).not.toContain('never been provisioned');
    // Not a version bump either: nothing here says the target moved.
    expect(text).not.toContain('STALE');
    expect(text).toContain('npx playwright install chromium');
  });

  it('does not call a half-installed build never provisioned', () => {
    // An install interrupted during extraction, or a cache provisioned for
    // another platform, leaves the directory for the very revision the
    // toolchain resolves with no executable inside it. Measured 2026-08-24 on
    // darwin/arm64: that cache was reported as "never been provisioned" to a
    // reader who could see `chromium-1234` sitting in it — the same
    // contradiction between the diagnosis and the visible cache that the
    // shell-only branch above exists to remove.
    const root = scratch('partial');
    const headed = lookedFor(runPreflight(root));
    // Walked with `dirname` rather than split on a separator, so the three-OS
    // matrix does not need a second code path here.
    let revisionDir = headed;
    while (dirname(revisionDir) !== root && dirname(revisionDir) !== revisionDir) {
      revisionDir = dirname(revisionDir);
    }
    expect(dirname(revisionDir), `${headed} is not under ${root}`).toBe(root);
    mkdirSync(revisionDir, { recursive: true });

    const result = runPreflight(root);
    expect(result.status).not.toBe(0);
    const text = markerLines(result).join('\n');
    expect(text).not.toContain('never been provisioned');
    expect(text).toContain('interrupted install');
    // Not a version bump either: the revision on disk is the one that is wanted.
    expect(text).not.toContain('STALE');
    expect(text).toContain('npx playwright install chromium');
  });

  it('fails when the headed build is present but the headless shell is not', () => {
    // A headless launch — which is what `playwright.config.ts` does — starts
    // `chromium_headless_shell-<rev>`, a SEPARATE download from the headed build
    // that `executablePath()` returns. Checking only the headed one answered a
    // question the suite never asks: this exact cache shape passed the preflight
    // and then failed at launch with `Executable doesn't exist`, the one error
    // the whole feature exists to pre-empt. A half-finished or `--no-shell`
    // install leaves it.
    const root = scratch('shell');
    stub(lookedFor(runPreflight(root)));

    const result = runPreflight(root);
    expect(result.status).not.toBe(0);
    const text = markerLines(result).join('\n');
    expect(text).toContain('headless-shell');
    expect(text).toContain('chromium_headless_shell-');
    expect(text).toContain('npx playwright install chromium');
    // Still one setup failure, and still nothing that reads as a visual diff.
    expect(text).toContain('not a visual regression');
    expect(result.stderr).not.toContain('browserType.launch');

    // And it clears once the shell is there, so the check cannot be permanently
    // red on a correctly provisioned cache.
    stub(join(lookedFor(result), 'stub'));
    expect(runPreflight(root).status).toBe(0);
  });

  it('exits 0 and says nothing when the browser is present', () => {
    // The real cache, read-only: if this machine is provisioned the preflight is
    // silent. If it is not, this test would report the same missing dependency the
    // feature exists to declare — which is the honest outcome, not a flake.
    const result = runPreflight(process.env['PLAYWRIGHT_BROWSERS_PATH'] ?? '');
    if (result.status === 0) {
      expect(markerLines(result)).toEqual([]);
    } else {
      expect(markerLines(result).join('\n')).toContain('npx playwright install chromium');
    }
  });
});

describe('visual preflight — it never goes green by not running (FR-R3-065)', () => {
  it('contains no install invocation, so it cannot auto-provision', () => {
    const body = read(PREFLIGHT);
    // Declaring a 95 MiB dependency is not the same as hiding it inside a gate;
    // FR-R3-045 declined the Electron download in `ci:fast` on the same grounds.
    // The command appears as TEXT in the remedy message, which is the point — so
    // this asserts it is never EXECUTED.
    expect(body).not.toMatch(/execFileSync|execSync|spawnSync|spawn\(|exec\(/);
    expect(body).not.toMatch(/child_process/);
  });

  it('never exits 0 on a miss, and never reports success', () => {
    const result = runPreflight(scratch('vacuity'));
    expect(result.status).not.toBe(0);
    // Whole words, not substrings. A bare `'ok'` search matched inside "looked
    // for" on the first run of this gate — the same false-positive class as a
    // verb matched inside a noun. A check that fires on its own remedy text is a
    // check nobody keeps.
    //
    // The resolved path is excluded for the same reason, one step further out: it
    // is a filesystem path, never a success claim, and it carries whatever words
    // the temp directory happens to contain. On macOS `tmpdir()` sits under a
    // two-character `/var/folders/<hash>/` segment, so `\bok\b` matches the
    // machine, not the script — a gate that goes red on somebody's cache path is
    // the same false positive this comment already records once.
    const output = `${result.stdout}\n${result.stderr}`
      .split('\n')
      .filter((line) => !line.includes('Looked for: '))
      .join('\n')
      .toLowerCase();
    for (const claim of [/\bpassed\b/, /\bskipping\b/, /\bskipped\b/, /\bok\b/, /\bsuccess\b/]) {
      expect(output, `matched ${claim}`).not.toMatch(claim);
    }
  });

  it('fails rather than assuming the browser is present when resolution is indeterminate', () => {
    // The refusal is in the script, at the one branch that cannot be reached by
    // redirecting a path: `resolveExpectedExecutable` returning null. Asserted
    // structurally because forcing it would mean breaking the Playwright package.
    const body = read(PREFLIGHT);
    expect(body).toContain('could not resolve the expected Chromium executable');
    expect(body).toContain('Refusing to assume the browser is present');
    // And it must be a fail(), not a warn-and-continue.
    const indeterminate = body.slice(body.indexOf('if (expected === null)'));
    expect(indeterminate.slice(0, 800)).toContain('fail([');
  });

  it('has not skipped or weakened any visual case', () => {
    const spec = read(VISUAL_SPEC);
    expect(spec).not.toMatch(/\b(?:test|describe)\.(?:skip|fixme|only)\b/);
    expect(spec).not.toMatch(/\btest\.setTimeout\(\s*0\s*\)/);
    // No case COUNT is asserted, and the reason is a measurement this gate got
    // wrong on its first run. The suite reports 18 cases from 4 literal `test(`
    // calls: the rest are generated by parameterised loops over themes, surfaces
    // and routes. A source-text count is therefore not the case count, and the
    // draft floor of 18 failed against an untouched suite. Pinning Playwright's
    // own reported count would mean spawning the runner from a lint gate, which
    // costs seconds on every PR to detect something review sees plainly.
    //
    // Residual, stated: a case DELETED outright is not caught here. What is
    // caught is the far likelier shape — a case silenced in place with `.skip`
    // or `.fixme` to get a chain green, which is the FR-R3-045 vacuity failure
    // this assertion exists for.
  });

  it('has not reordered the chains or moved the visual step out of the preflight', () => {
    const manifest = JSON.parse(read('package.json')) as { scripts: Record<string, string> };
    // `test:visual`'s presence in `ci:fast` is what made REL-N1 locally
    // observable (FR-R3-021). Dropping it would make this whole feature moot.
    expect(manifest.scripts['ci:fast']).toContain('test:visual');
    expect(manifest.scripts['ci']).toContain('test:visual');
    // ORDER, not the exact string. Pinning the whole script with `toBe` made an
    // unrelated edit — a reporter flag, a renamed config — fail a gate whose
    // stated subject is ordering. Assert the three positions that actually
    // matter and let the rest of the script change freely.
    const visual = manifest.scripts['test:visual'];
    const preflightAt = visual.indexOf('check-playwright-browser');
    const buildAt = visual.indexOf('build:webview');
    const runnerAt = visual.indexOf('playwright test');
    expect(preflightAt, 'test:visual no longer runs the browser preflight').toBeGreaterThanOrEqual(0);
    expect(buildAt, 'test:visual no longer builds the webview').toBeGreaterThan(-1);
    expect(runnerAt, 'test:visual no longer runs the Playwright runner').toBeGreaterThan(-1);
    // The preflight must come FIRST — reporting before the runner starts is the
    // entire deliverable, and a preflight after the build makes a contributor
    // wait for a build to be told they cannot run.
    expect(preflightAt).toBeLessThan(buildAt);
    expect(buildAt).toBeLessThan(runnerAt);
  });
});
